version: "3"
services:
  node-red:
    build: node-red/.
    restart: always
    ports:
      - "127.0.0.1:1880:1880"
    volumes:
      - ./node-red/data:/data
    user: root
  mosquitto:
    image: "eclipse-mosquitto"
    restart: always
    ports:
      - 1883:1883
    expose:
      - 1883
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    #      - /etc/letsencrypt/live/bioreactor.hackuarium.org:/mosquitto/letsencrypt
    user: root
  influxdb:
    image: "influxdb:1.7.9"
    restart: always
    expose:
      - 8086
    volumes:
      - ./influxdb/db:/var/lib/influxdb
    environment:
      INFLUXDB_DB: data
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
    user: root
